### ISSUE TITLE
Why part of the repository? node_modules, bin and obj directory

### ISSUE THREAD

**Issue by rioj7** [PacktPublishing/Developing-Multi-platform-Apps-with-Visual-Studio-Code#1]
What is the need to have the following directories in the repository:

* `Chapter03/NodeJSAPI/node_modules/`
* `Chapter03/PythonAPI/__pycache__/`
* `Chapter03/PythonAPI/env/`
* `Chapter04/NetCoreAPI/bin/`
* `Chapter04/NetCoreAPI/obj/`

All these directories contain generated or downloaded content. Together about 100MB of unneeded stuff.

For the python environment in `Chapter03/PythonAPI/env/` better to make a `requirements.txt` file with

```
pip freeze >requirements.txt
```

And put that in the repository.

**Comment by ankx06** [comment]
It should not be there. We will add a .gitignore file.

**Comment by rioj7** [comment]
As these files still stay/are in the repository you should start over with the correct `.gitignore` file.
